[env]
TERM = "alacritty"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "OnlyLeft"

[font]
offset.y = 1
glyph_offset.y = 3

[font.normal]
family = "Monaspace Krypton NF ExtraLight"


[colors.primary]
background = "#000000"

